### PR TITLE
[release-4.11] UPSTREAM: google/cadvisor: 3301: Request the pid of another container if current pid is not longer valid

### PR DESCRIPTION
**Pull request by harche**
https://github.com/google/cadvisor/pull/3301

xref https://issues.redhat.com/browse/OCPBUGS-4053

### CODE REVIEW

**Comment by haircommander** [comment]
I say let's wait on 4.12 version to be verified to prevent regressions

**Comment by harche** [comment]
4.12 [bug](https://issues.redhat.com/browse/OCPBUGS-14745) is now verified.

**Pull request merged**
